# render.yaml
services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: ""  # Leave empty for PHP environment
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: <your-app-key-here>
      - key: APP_URL
        value: https://<your-site-name>.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <your-db-host>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <your-db-name>
      - key: DB_USERNAME
        value: <your-db-username>
      - key: DB_PASSWORD
        value: <your-db-password>
